var express = require("express");
var bodyParser = require("body-parser");
var mongoose = require("mongoose");
const path = require("path")
const nodemailer = require("nodemailer")

const app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

app.use(express.static("public"));

mongoose
  .connect("mongodb+srv://admin:admin123@siamaq.h4fjfrg.mongodb.net/mail", {
    useNewUrlParser: true,
  })
  .then(() => console.log("mongoDb Is Connected"))
  .catch((err) => console.log(err));

  // app.get("/frontend", (req, res)=>{
  //   res.sendFile(path.resolve(__dirname, "public", "index.html"))
  // })

var nameSchema = new mongoose.Schema({

  name: String,
  email: String,
  mobileNo: Number,
  message: String,

});

var User = new mongoose.model("mail", nameSchema);

app.post("/handleData", async (req, res) => {
  console.log(req.body);
  if (Object.keys(req.body).length <= 0) {
    console.log("error");
  }
  var myData = await User.create(req.body);
  console.log(myData)

  var transport = nodemailer.createTransport({
    host: "relay.mailbaby.net",
    port: 587,
    auth: {
        user: "mb20059", //example of generated by Mailtrap
        pass: "sKDua7fCmK54we5d3kFK" //example of generated by Mailtrap
    }
});

var mailOptions = {
  from: 'suraj@siamaq.live',
  to: 'rahulkumarkiit94@gmail.com',
  subject:"review message",
  html:`${myData.message}`
};

transport.sendMail(mailOptions, (error, info) => {
  if (error) {
      return console.log(error);
  }
  console.log('Email sent: ' + info.response);
});

});

let port = 5000;

app.listen(port, () => {
  console.log(`Server is running on port ${port}.`);
});
